-- =====================================================================
-- 0. LIMPIEZA DE TABLAS Y CONFIGURACIONES PREVIAS (DROP)
-- =====================================================================

-- Eliminar en cascada las tablas previas para reiniciar el esquema limpio
drop table if exists public.properties cascade;
drop table if exists public.profiles cascade;

-- Eliminar triggers y funciones asociadas
drop trigger if exists on_auth_user_created on auth.users;
drop function if exists public.handle_new_user cascade;


-- =====================================================================
-- 1. TABLA DE PERFILES (profiles) Y TRIGGERS DE AUTH
-- =====================================================================

create table public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  name text not null,
  email text,
  role text not null default 'CLIENT' check (role in ('ADMIN', 'AGENT', 'CLIENT')),
  is_active boolean not null default true,
  created_at timestamptz default now()
);

-- Trigger para crear perfil automáticamente al registrar un usuario nuevo
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, email, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', 'Usuario'),
    new.email,
    coalesce(new.raw_user_meta_data->>'role', 'CLIENT')
  );
  return new;
end;
$$ language plpgsql security definer;

-- Crear el trigger en auth.users
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Helper functions to bypass RLS recursion
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'ADMIN' and is_active = true
  );
end;
$$ language plpgsql security definer set search_path = public;

create or replace function public.is_agent_or_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('AGENT', 'ADMIN') and is_active = true
  );
end;
$$ language plpgsql security definer set search_path = public;

-- Habilitar seguridad a nivel de fila (Row Level Security) en profiles
alter table public.profiles enable row level security;

-- Políticas RLS para profiles
create policy "Usuarios ven su propio perfil"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Solo ADMIN ve todos los perfiles"
  on public.profiles for select
  using (public.is_admin());

create policy "Solo ADMIN actualiza perfiles"
  on public.profiles for update
  using (public.is_admin());


-- =====================================================================
-- 2. TABLA DE PROPIEDADES (properties) CON COLUMNAS ORIGINALES
-- =====================================================================

create table public.properties (
  id bigint generated by default as identity primary key,
  title text not null,
  location text,
  description text,
  price numeric not null,
  price_formatted text,
  type text,
  subtype text,
  operation text,
  rooms integer,
  baths integer,
  garages integer,
  area numeric,
  stratum integer,
  floor integer,
  year integer,
  private_area numeric,
  furnished boolean default false,
  pets boolean default true,
  images text[] default '{}',
  exclusive boolean default false,
  status text not null default 'Disponible' check (status in ('Disponible', 'Vendido', 'Arrendado')),
  is_active boolean not null default true,
  agent_id uuid references public.profiles(id),
  created_at timestamptz default now()
);

-- Habilitar seguridad a nivel de fila (Row Level Security) en properties
alter table public.properties enable row level security;

-- 1. Cualquiera puede VER propiedades activas (público)
create policy "Propiedades activas son públicas"
  on public.properties for select
  using (is_active = true);

-- 2. Solo ADMIN y AGENT pueden CREAR propiedades
create policy "ADMIN y AGENT crean propiedades"
  on public.properties for insert
  with check (public.is_agent_or_admin());

-- 3. AGENT solo edita SUS propiedades, ADMIN edita todas
create policy "AGENT edita sus propiedades, ADMIN edita todas"
  on public.properties for update
  using (
    auth.uid() = agent_id
    or public.is_admin()
  );

-- 4. Solo ADMIN puede eliminar propiedades
create policy "Solo ADMIN elimina propiedades"
  on public.properties for delete
  using (public.is_admin());

-- =====================================================================
-- 3. TABLA DE CONFIGURACIONES (settings) PARA INFORMACIÓN DE CONTACTO
-- =====================================================================
create table if not exists public.settings (
  key text primary key,
  value text not null
);

alter table public.settings enable row level security;

create policy "Settings son públicas"
  on public.settings for select
  using (true);

create policy "Solo ADMIN modifica settings"
  on public.settings for all
  using (public.is_admin());

-- Insertar valores por defecto si no existen
insert into public.settings (key, value) values 
  ('phone', '573002510313'),
  ('email', 'cr7inmobiliaria@gmail.com')
on conflict (key) do nothing;


-- =====================================================================
-- 4. CONFIGURACIÓN DE STORAGE (Buckets y Políticas de RLS en storage.objects)
-- =====================================================================

-- 1. Crear el bucket público 'property-images' si no existe
insert into storage.buckets (id, name, public)
values ('property-images', 'property-images', true)
on conflict (id) do nothing;

-- 2. Eliminar políticas previas para evitar duplicidad o conflictos al re-ejecutar
drop policy if exists "Imágenes de propiedades públicas para select" on storage.objects;
drop policy if exists "Usuarios autenticados insertan imágenes" on storage.objects;
drop policy if exists "Usuarios autenticados actualizan imágenes" on storage.objects;
drop policy if exists "Usuarios autenticados eliminan imágenes" on storage.objects;

-- 3. Crear políticas sobre storage.objects para el bucket 'property-images'
create policy "Imágenes de propiedades públicas para select"
  on storage.objects for select
  using (bucket_id = 'property-images');

create policy "Usuarios autenticados insertan imágenes"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'property-images');

create policy "Usuarios autenticados actualizan imágenes"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'property-images');

create policy "Usuarios autenticados eliminan imágenes"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'property-images');


-- =====================================================================
-- 5. TABLA DE VISITAS (visits) PARA AGENDAR CITAS
-- =====================================================================
create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id) on delete cascade,
  name text not null,
  phone text not null,
  visit_date date not null,
  message text,
  created_at timestamptz default now()
);

-- Habilitar RLS en visits
alter table public.visits enable row level security;

-- Cualquiera puede insertar (agendar) una visita
create policy "Cualquiera agenda visitas"
  on public.visits for insert
  with check (true);

-- Solo ADMIN y AGENT pueden ver visitas
create policy "ADMIN y AGENT ven visitas"
  on public.visits for select
  using (public.is_agent_or_admin());

-- Solo ADMIN puede eliminar registros de visitas
create policy "Solo ADMIN elimina visitas"
  on public.visits for delete
  using (public.is_admin());


